basePath: '{{.BasePath}}'
definitions:
  models.Base:
    properties:
      error:
        type: string
      success:
        type: boolean
    type: object
  models.SecretResponse:
    properties:
      createdAt:
        type: string
      expiresAt:
        type: string
      hash:
        type: string
      remainingViews:
        type: integer
      secretText:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /:
    get:
      description: Welcome will return the welcome message as response with status
        code as 200
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Base'
            type: object
      summary: Welcome
      tags:
      - System status
  /ping:
    get:
      description: Ping test, return the commit ID and container ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Base'
            type: object
      summary: Ping test
      tags:
      - System status
  /secret:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Add a new secret
      parameters:
      - description: This text will be saved as a secret
        in: formData
        name: secret
        required: true
        type: string
      - description: The secret won't be available after the given number of views.
          It must be greater than 0.
        in: formData
        name: expireAfterViews
        required: true
        type: integer
      - description: The secret won't be available after the given time. The value
          is provided in minutes. 0 means never expires
        in: formData
        name: expireAfter
        required: true
        type: integer
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SecretResponse'
            type: object
      summary: Add a new secret
      tags:
      - secret
  /secret/{hash}:
    get:
      description: Get a secret by ID
      parameters:
      - description: Unique hash to identify the secret
        in: path
        name: hash
        required: true
        type: string
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SecretResponse'
            type: object
      summary: Get a secret by ID
      tags:
      - secret
  /status:
    get:
      description: Status will provide the status of the service we been used in the
        application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Base'
            type: object
      summary: Get Status
      tags:
      - System status
swagger: "2.0"
